export const GET_TOP_HEADLINES_SUCCESS = "GET_TOP_HEADLINES_SUCCESS";
export const GET_TOP_HEADLINES_REQUEST = "GET_TOP_HEADLINES_REQUEST";
export const BUSINESS_NEWS = "BUSSINESS_NEWS"
export const TECHNOLOGY_NEWS = "TECHNOLOGY_NEWS"
export const SEARCH_NEWS = "SEARCH_NEWS"
export const SELECTED_SOURCE = "SELECTED_SOURCE"

